services:
  - type: web
    name: discord-bot
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        fromSecret: DISCORD_TOKEN  # Render の Secrets に登録済みのトークン
      - key: YDL_COOKIES_PATH
        fromSecret: YDL_COOKIES_PATH  # yt-dlp 用の cookies パスが必要なら
