services:
  - type: web
    name: discord-music-bot
    env: docker
    plan: starter # 無料枠
    repo: https://github.com/ghjri23/bot # GitHub リポジトリURL
    branch: main
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        value: "<ここにDiscord Bot Tokenを入力>"
    dockerContext: .
    dockerCommand: python bot.py
